
import { Movie } from '@/types/Movie';

export const FALLBACK_MOVIES: Movie[] = [
  {
    id: 550,
    title: 'Fight Club',
    year: 1999,
    genres: ['Drama', 'Thriller'],
    posterUrl: 'https://images.unsplash.com/photo-1594908900066-3f47337549d8?w=500',
    synopsis: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more. A mind-bending journey through consumerism, masculinity, and identity.',
    imdbRating: 8.8,
    rottenTomatoesScore: 79,
    redditScore: 92,
    runtimeMinutes: 139,
  },
  {
    id: 13,
    title: 'Forrest Gump',
    year: 1994,
    genres: ['Drama', 'Romance'],
    posterUrl: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=500',
    synopsis: 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    imdbRating: 8.8,
    rottenTomatoesScore: 71,
    redditScore: 88,
    runtimeMinutes: 142,
  },
  {
    id: 155,
    title: 'The Dark Knight',
    year: 2008,
    genres: ['Action', 'Thriller', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500',
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    imdbRating: 9.0,
    rottenTomatoesScore: 94,
    redditScore: 95,
    runtimeMinutes: 152,
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    year: 1994,
    genres: ['Thriller', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1574267432644-f610f5ac3b5c?w=500',
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption. A groundbreaking film that redefined independent cinema.',
    imdbRating: 8.9,
    rottenTomatoesScore: 92,
    redditScore: 91,
    runtimeMinutes: 154,
  },
  {
    id: 27205,
    title: 'Inception',
    year: 2010,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    posterUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=500',
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O. A visually stunning exploration of dreams within dreams.',
    imdbRating: 8.8,
    rottenTomatoesScore: 87,
    redditScore: 93,
    runtimeMinutes: 148,
  },
  {
    id: 278,
    title: 'The Shawshank Redemption',
    year: 1994,
    genres: ['Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=500',
    synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. A timeless tale of hope and friendship.',
    imdbRating: 9.3,
    rottenTomatoesScore: 91,
    redditScore: 96,
    runtimeMinutes: 142,
  },
  {
    id: 238,
    title: 'The Godfather',
    year: 1972,
    genres: ['Drama', 'Thriller'],
    posterUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=500',
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son. An epic tale of family, power, and the American Dream.',
    imdbRating: 9.2,
    rottenTomatoesScore: 97,
    redditScore: 94,
    runtimeMinutes: 175,
  },
  {
    id: 424,
    title: 'Schindler&apos;s List',
    year: 1993,
    genres: ['Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=500',
    synopsis: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    imdbRating: 9.0,
    rottenTomatoesScore: 98,
    redditScore: 89,
    runtimeMinutes: 195,
  },
  {
    id: 19404,
    title: 'Dilwale Dulhania Le Jayenge',
    year: 1995,
    genres: ['Comedy', 'Drama', 'Romance'],
    posterUrl: 'https://images.unsplash.com/photo-1524712245354-2c4e5e7121c0?w=500',
    synopsis: 'When Raj meets Simran in Europe, it isn&apos;t love at first sight but when Simran moves to India for an arranged marriage, love makes its presence felt. A Bollywood classic that defined romance for a generation.',
    imdbRating: 8.1,
    rottenTomatoesScore: 89,
    redditScore: 85,
    runtimeMinutes: 189,
  },
  {
    id: 129,
    title: 'Spirited Away',
    year: 2001,
    genres: ['Animation', 'Family', 'Mystery'],
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500',
    synopsis: 'During her family&apos;s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts. A magical journey of courage and self-discovery.',
    imdbRating: 8.6,
    rottenTomatoesScore: 97,
    redditScore: 90,
    runtimeMinutes: 125,
  },
];
